### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by EweLoHD** [GuidodiPasquo/PID-Simulator#1]
Hey, would it be possible to have some sort of guide on how to install/run your software. I'm not that experienced in python and have therefore some issues with getting your software to work. 

Thanks in advance!

**Comment by GuidodiPasquo** [comment]
Yes, of course!
First you need to install python, this video explains it very well
https://www.youtube.com/watch?v=UvcQlPZ8ecA
(It's the same method for the version 3.9.1, remember check "add to path" and in the optional features: install pip and install td/tk)

Once you have python installed, you just have to install the dependencies from the command prompt (just type cmd in the windows search bar)
To do that, just type the following lines and press enter after each of them
pip install numpy
pip install matplotlib
pip install pandas
pip install vpython
pip3 install pyserial
![Screenshot_15](https://user-images.githubusercontent.com/65097298/107101923-9176d800-67f7-11eb-93bc-17a7aa1d652d.png)

To run the program, download the code as zip and extract it in the folder you want.
Once it's done, open the command prompt and type:
cd (And the path you choose)
![Screenshot_1](https://user-images.githubusercontent.com/65097298/107102040-f6cac900-67f7-11eb-9b30-8b70a062b63c.png)

Press enter and type:
python main.py
![Screenshot_2](https://user-images.githubusercontent.com/65097298/107102409-2dedaa00-67f9-11eb-9b29-7ade561fb0c0.png)

Press enter again and the program should start.

**Comment by EweLoHD** [comment]
Thank you! This is a very clear guide. It works now I previously just forgot to install a module. 
Thank you very much for helping me and also thank you for the work and effort you put into this project!!
